### ISSUE TITLE
Can't seem to catch errors on Serial.open()

### ISSUE THREAD

**Issue by Tmp2k** [nebrius/raspi-serial#13]
If there is an error opening the port (e.g. invalid device/path) then I get the following error...

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

I've tried catching the error in the usual manner, `try{} catch(e) {}`, and prefixing the open function with `await` and putting `.catch()` on the end, but the function appears to not be async.

So what's the best way to catch the error?

I just want to try and open a port and execute some code on the callback (this works) or if the port couldn't open then do something else.

**Comment by nebrius** [comment]
Unfortunately you can't, and honestly I wouldn't recommend using any sort of try/catch logic to catch this anyways, because this is an unrecoverable error. Once it's actually time to open a serial port inside of raspi-serial, enough state is set up that raspi-serial would be left in a broken state if the script kept on running.

The better option is to try and test if a port can be opened first before actually trying to open it. This can be done by using [@serialport/list](https://www.npmjs.com/package/@serialport/list) to check if the port exists or not, and then you can use node.js core methods (in `fs` I believe) to validate file permissions.

**Comment by Tmp2k** [comment]
Perfect, that would better suit my situation better. I'm literally scanning all the available serial ports for a certain device. I was relying on a list of generic paths, but using serialport/list, I can just enumerate all the serial ports on the Pi and scan them. 

Thanks!

P.S. If you're interested, this is the project [pxltbl](https://github.com/NemiahUK/pxltbl). it uses a RasPi to talk to an Arduino/Teensy at 1,000,000 baud to drive an RGB pixel display the size of a coffee table.

**Comment by nebrius** [comment]
> P.S. If you're interested, this is the project pxltbl. it uses a RasPi to talk to an Arduino/Teensy at 1,000,000 baud to drive an RGB pixel display the size of a coffee table.

That looks amaaaazing!! 😍
