### ISSUE TITLE
serialport 4.0.5 broken

### ISSUE THREAD

**Issue by goliatone** [nebrius/raspi-serial#2]
See `serialport` issues [1004][1] and [1005][2]. 
I would recommend to tie `raspi-serial` dependency to a specific version. Specially since this is a dependency of a dependency of a dependency for most people.

For instance:
```
    "serialport": "4.0.3"
```

[1]:https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1004
[2]:[1]:https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1005

**Comment by nebrius** [comment]
I get the desire to do this, but the unfortunate reality is that I don't spend a lot of time on raspi-io these days since it's basically feature complete and doesn't really need a whole lot of maintenance. If we tie serialport to a specific version, _it will get behind_. Indeed, using `^` still allowed it to get two major versions behind and was only recently updated.

It sounds like a fix for serialport will be out soon, reading the thread, so I recommend hanging tight.

If this is a blocker, you can roll raspi-io back to 6.1.0 to use the old version of serialport.

**Comment by goliatone** [comment]
I was building a docker image on a raspberry pi zero, each build took 4 hours, and it took a few builds to figure out that raspi-io was pulling in raspi-serial which in turn was pulling in its own version of serialport. It stopped working from one build to the next without a **changing in the project's code base**.

> raspi-io ... it's basically feature complete
> If we tie serialport to a specific version, it will get behind.

Behind what? Since raspi-io is feature complete, it would just be stable and tied to a version of serialport that we know it works. 

I have a fork of both raspi-io and raspi-board, will keep using those on my projects. 

Anyways, thank you for all your projects!

**Comment by nebrius** [comment]
> Behind what? Since raspi-io is feature complete, it would just be stable and tied to a version of serialport that we know it works.

This would work well if Node and Ubuntu were also stable targets, but they're not. The old versions of serialport were causing deprecation warnings to be thrown by V8. Due to the nature of serialport being a native module, not a JavaScript only module, it's much more prone to breakage due to only upgrading Node. If we leave as is, raspi-io would stop working entirely at some point in time (indeed I think it was broken on Node 7).

**Comment by nebrius** [comment]
> I have a fork of both raspi-io and raspi-board, will keep using those on my projects.

I think this is totally reasonable, especially since docker isn't a supported platform of raspi-io (technically only Raspbian running on bare metal is supported).

> Anyways, thank you for all your projects!

<3

**Comment by nebrius** [comment]
Oh, so I was just checking, and serialport 4.0.6 is out with a fix, so it should work for you now.

**Comment by goliatone** [comment]
> docker isn't a supported platform of raspi-io 

Other people were having the same issue on _normal_ Raspbian :)

Thanks for the updates

**Comment by nebrius** [comment]
Closing as the bug has been fixed in serialport
